name: 'build test'

on: [pull_request, push]

jobs:
  verify:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout...
        uses: actions/checkout@v4

      - name: Set up JDK...
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and test server...
        run: cd jersey-server-example && mvn -ntp clean verify

      - name: Build and test client...
        run: cd jersey-client-example && mvn -ntp clean verify